### ISSUE TITLE
Using template maps as "sphere_map_fn" parameter

### ISSUE THREAD

**Issue by lumyus** [rjdmoore/fictrac#14]
Hello,

I am currently working with Fictrac and everything works well so far. Really appreciate the work! 

There is a parameter called _"sphere_map_fn"_ which is intended to point to a map of the ball. I tried using the generated map _"X-template.png"_ as input to _"sphere_map_fn"_ while leaving all other params in the _config.txt_ file the same. 

However Fictrac get stuck on the _"global search"_ and never gets passed the first frame. Any suggestions on what I should change or what might be causing this issue?

Thanks!

**Comment by rjdmoore** [comment]
Hmm, you should have at least set opt_do_global

Does this solve the issue?

**Comment by lumyus** [comment]
Yes I set opt_do_global.  The console output gets stuck at the following: 

_Warning! Using default value for save_raw (0).
Frame 0
Doing global search_

**Comment by rjdmoore** [comment]
Can you send me the debug output log, and ideally the input video and
config file that are causing the problem?

This feature is unfortunately a little poorly tested in the newer versions
as I don't think many use it.

Can I ask what your reason for using this feature is?

**Comment by lumyus** [comment]
Actually we managed to get it to work. It can take a very long time for the global search to find the correct starting point. But that's okay. Anyway consider this as resolved.  Btw this is a really cool project and helps are lab big time. Thanks again!
