### ISSUE TITLE
Fictrac + Spinnaker build

### ISSUE THREAD

**Issue by alexanderbates** [rjdmoore/fictrac#15]
I am trying to make FicTrac with 

```
cmake -A x64 -D CMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -D PGR_USB3=ON -D PGR_DIR="C:\Program Files\FLIR Systems\Spinnaker" ..
```

And I get the error: 

```
CMake Error at CMakeLists.txt:79 (get_filename_component):
  get_filename_component called with incorrect number of arguments


-- Configuring incomplete, errors occurred!
See also "C:/dev/fictrac/build/CMakeFiles/CMakeOutput.log".
```

This is the offending line
```
get_filename_component(PGR_LIB ${PGR_DIR} DIRECTORY)
```

But I think the core issue is that FicTrac cannot find Spinnaker_v140.lib, and indeed I found this reddit post: https://www.reddit.com/r/fictrac/comments/ashx3b/error_compiling_fictrac_20_with_spinnaker_on/ but the README didn't mention it! Spinnaker needs to be installed with the Application Development option.

**Comment by rjdmoore** [comment]
Which cmake version do you have?

**Comment by alexanderbates** [comment]
Sorry @rjdmoore , I hit enter a few times before the post was ready by accident, as I was debugging. I found my issue has already been flagged on Reddit a few years back, and I had not installed Spinnaker with the Application Development option!

**Comment by alexanderbates** [comment]
Thxs for the great software btw, I am looking forward to using it
