### ISSUE TITLE
Output video saved with incorrect duration

### ISSUE THREAD

**Issue by GBarnum** [rjdmoore/fictrac#19]
The raw video output by fictrac (with 'save_raw : y') is saved with the incorrect duration information. For example, one file is reported to be 06:27:22.87, both by VLC media player, and ffprobe, however, playing or converting the file using VLC results in 10:21:40.07 of video, which corresponds to the correct number of frames (and the additional video is correct and intact).

This also results in the loss of the additional video information if the video file is used as an input to fictrac to redo the tracking.

**Comment by rjdmoore** [comment]
see [here](https://github.com/rjdmoore/fictrac/blob/14fe931543fd33807ba5a7c96a4e5f561f93bf6e/src/Trackball.cpp#L489) for how output raw video is created. FicTrac tries to get the FPS from the source, and failing that will use the fps specified in the config file, or as a last resort just assume 25 fps.

If your source framerate is varying, this will in any case not be represented in the output raw video, and may lead to discrepancies with the duration - but all frames should be present in the output video.

If your input framerate is higher than FicTrac's processing framerate, then some frames may be dropped from the output video. This may not cause discrepancy in duration, but those frames would be lost for future processing.
