### ISSUE TITLE
Issue while plotting ROI

### ISSUE THREAD

**Issue by owadhwa** [rjdmoore/fictrac#21]
I am trying to plot the ROI computed by fictrac in the configGui. For this, I need the center and radius information of the sphere. How is this stored in the configuration parameters document? How is roi_c computed by fictrac?What are the three coordinates in the roi_r parameter?

**Comment by rjdmoore** [comment]
These parameters are described [here](https://github.com/rjdmoore/fictrac/blob/master/doc/params.md).

roi_r is the radius in radians of the trackball ROI.
roi_c is a three element vector which is the direction to the centre of the trackball in the camera coordinate frame. 

If you know the centre of the trackball in pixel coordinates and want to find the corresponding 3-element view vector, then you could see for example [this function](https://github.com/rjdmoore/fictrac/blob/14fe931543fd33807ba5a7c96a4e5f561f93bf6e/src/RectilinearCameraModel.cpp#L72) for a rectilinear camera-lens, or [corresponding function](https://github.com/rjdmoore/fictrac/blob/14fe931543fd33807ba5a7c96a4e5f561f93bf6e/src/FisheyeCameraModel.cpp#L74) for fisheye lens in
