### ISSUE TITLE
Are TCP sockets still an option for newer versions of Fictrac?

### ISSUE THREAD

**Issue by MarkGalperin** [rjdmoore/fictrac#23]
My lab uses a previous commit of fictrac (before UDP was default) to enable TCP communication which is convenient for our systems as TCP servers must wait for the client program before starting acquisition and this allows us to trigger fictrac without waiting for initialization. Unlike TCP, UDP starts broadcasting right away, and I don't see any configuration parameters or build settings that revert fictrac to TCP. How can I configure the current version of fictrac to use TCP by default?

**Comment by rjdmoore** [comment]
Change [this line](https://github.com/rjdmoore/fictrac/blob/14fe931543fd33807ba5a7c96a4e5f561f93bf6e/src/SocketRecorder.cpp#L7) to 
```
#if 1
```
to use TCP instead of UDP.
