### ISSUE TITLE
Enter key not detected in ConfigGUI

### ISSUE THREAD

**Issue by sgherbst** [rjdmoore/fictrac#3]
Thanks again for your work on fictrac!  We encountered an error in ConfigGUI on Ubuntu 18.04 LTS in which the "Enter" key is not detected while going through the configuration process.  It seems that the reason is because the keycode for "Enter" is 0x0d in our setup, rather than 0x0a (the value selected because this isn't a Windows machine).  Perhaps the program should accept either 0x0d or 0x0a?

**Comment by rjdmoore** [comment]
The key code should be set depending on the operating system. See [source code](https://github.com/rjdmoore/fictrac/blob/74de298fb1bce1e1cba3a921219a5bddccb64784/src/ConfigGUI.cpp#L429).

Can you confirm that the code version you are running includes these lines?

**Comment by sgherbst** [comment]
Yes, our version includes those lines but our non-WIN32 setup produces key code 0x0d when Enter is pressed.

**Comment by rjdmoore** [comment]
Ok, I've changed the config GUI to always accept both forms - as you suggested.

You'll find the [change](https://github.com/rjdmoore/fictrac/commit/31fc5846df67a48ff0533f287b93a9d9232464cc) in the develop branch
