### ISSUE TITLE
Basler USB3 camera support

### ISSUE THREAD

**Issue by rjdmoore** [rjdmoore/fictrac#5]
Enable support for Basler USB3 cameras either via Pylon SDK or USB3 Vision standard.

**Comment by young24** [comment]
May I help you with this Basler support? I have some experience with Basler Pylon. I wrote a library for talking to Basler USB cameras. Details are here([cpp](https://github.com/Wenlab/BLITZ/blob/reconstruction/MyLibs/talk2camera.cpp) and [h file](https://github.com/Wenlab/BLITZ/blob/reconstruction/MyLibs/talk2camera.h)).

**Comment by rjdmoore** [comment]
Yes please, if you have some capture code. There isn't much work needed, I just haven't gotten around to writing the necessary code or getting a Basler cam to test with.

All that is needed is a class (e.g. BaslerSource.cpp/.h) that is similar to PGRSource and that extends the FrameSource interface. FicTrac only supports frame grabbing and getting FPS from the camera for PGR/CV sources, so the BaslerSource only needs to support the same (other camera functions can be configured externally).

To contribute, you just need to follow the standard [fork and pull request workflow](https://gist.github.com/rjdmoore/ed014fba0ee2c7e75060ccd01b726cb8).

**Comment by young24** [comment]
Okay, I have a Basler camera at hand. It would not be difficult for me to write such an API. 😃

**Comment by rjdmoore** [comment]
implemented as of [2.1.1](https://github.com/rjdmoore/fictrac/tree/2a62be0fd344e9432b4e7d5f029a1f5c9c4d7b70)
